### ISSUE TITLE
Multiplying U2048 by U2048 to get U4096

### ISSUE THREAD

**Issue by ycscaly** [RustCrypto/crypto-bigint#209]
I am preparing to write code of (threshold) Paillier using `crypto-bigint`, and was wondering how to go about operations between different bit sizes. I understand that in `crypto-bigint` the size of the integer is fixed at compilation, however it should be possible to transition between types - so that multiplying two numbers of a given size gives you a number double that size.

However, I have not found any way to do that currently. This is a sketch of what I figured out was possible with the current API:
```
let P = crypto_primes::prime::<16>(1024);
let Q = crypto_primes::prime::<16>(1024);
let (N_low, N_high) = P.mul_wide(&Q);
let N_limbs: [Limb; 32] = concat_arrays!(N_low.to_limbs(), N_high.to_limbs());
let N = U2048::from(N_limbs);

let N2_low, N2_high = N.mul_wide(&N);
let N2_limbs: [Limb; 64] = concat_arrays!(N2_low.to_limbs(), N2_high.to_limbs());
let N2 = U4096::from(N2_limbs);
```
Is this the right approach? can we think about adding appropriate functions?

**Comment by tarcieri** [comment]
See `Uint::square` as an example: https://github.com/RustCrypto/crypto-bigint/blob/master/src/uint/mul.rs#L78-L85

I'm not sure what `concat_arrays!` is, but `crypto-bigint` has its own `Concat` trait which is impl'd for `Uint`: https://docs.rs/crypto-bigint/latest/crypto_bigint/trait.Concat.html

The reason `mul_wide` doesn't use it yet is because it's a `const fn` and `const impl Trait` isn't stable.

It might be possible to add a function that does the `concat` for you based on the output of `Uint::mul_wide`, similar to how `square` vs `square_wide` works.

**Comment by ycscaly** [comment]
Ok perfect, it made no sense that nothing like this was available and indeed I have just missed it - `concat` looks like what I need.

Regarding your suggestion, it definitely would be prettier to add such a `mul` function. I'm willing to do a PR, it seems easy enough, or if you rather take it that's even better.

Thank you!
