### ISSUE TITLE
impl_modulus interaction with generic_const_exprs

### ISSUE THREAD

**Issue by WizardOfMenlo** [RustCrypto/crypto-bigint#245]
Hi, I have encountered the following bug (or at least unexpected behaviour). 
`impl_modulus` and `generic_const_exprs` do not seem to mix well together. 
With the following code: 

```
#![feature(generic_const_exprs)]
use crypto_bigint::{impl_modulus, U64};
impl_modulus!(RingInteger, BackendInteger, "30e4b8f030ab42f3");
```
I get a E0207 error claiming: 'the const parameter `DLIMBS` is not constrained by the impl trait, self type, or predicates'. 
Removing generic_const_exprs fixes it.  Since the feature is unstable, this might not be intended usage of the library, but it would be great if it worked :)

**Comment by tarcieri** [comment]
That sounds like a bug in `generic_const_exprs`.

Anything that works on stable Rust today should continue to work even with new features enabled, and if not it's a bug in rustc.

If you have suggestions about how we can work around the issue, we can consider them, but otherwise nightly is a moving target and `generic_const_exprs` is currently expected to have bugs.
